# ruff: noqa: E501
from __future__ import annotations

import asyncio
import json
from typing import Any

from sqlalchemy import text

from vav.core.config import get_settings
from vav.core.database import session_factory

SUBSCRIPTIONS: tuple[tuple[Any, ...], ...] = (
    (
        "auth-registration-user-v1",
        "auth.registration.created",
        "verify_email",
        "account",
        "normal",
        "event_user",
        "verify-email",
        "transactional_required",
        ["email"],
        [],
    ),
    (
        "auth-activated-user-v1",
        "auth.email_verification.completed",
        "account_activated",
        "account",
        "normal",
        "event_user",
        "account-activated",
        "transactional_required",
        ["in_app"],
        [],
    ),
    (
        "auth-password-changed-user-v1",
        "auth.password.changed",
        "password_changed",
        "security",
        "urgent",
        "event_user",
        "password-changed",
        "mandatory_security",
        ["in_app", "email"],
        [],
    ),
    (
        "auth-password-reset-user-v1",
        "auth.password.reset.completed",
        "password_reset_completed",
        "security",
        "urgent",
        "event_user",
        "password-reset-completed",
        "mandatory_security",
        ["in_app", "email"],
        [],
    ),
    (
        "auth-reuse-user-v1",
        "auth.refresh_token.reuse_detected",
        "suspicious_session",
        "security",
        "urgent",
        "event_user",
        "suspicious-session",
        "mandatory_security",
        ["in_app", "email"],
        [],
    ),
    (
        "commerce-order-created-user-v1",
        "order.created",
        "order_created",
        "order",
        "normal",
        "order_owner",
        "order-created",
        "transactional_required",
        ["in_app"],
        ["email"],
    ),
    (
        "commerce-payment-succeeded-user-v1",
        "payment.succeeded",
        "payment_succeeded",
        "payment",
        "normal",
        "order_owner",
        "payment-succeeded",
        "transactional_required",
        ["in_app", "email"],
        [],
    ),
    (
        "commerce-payment-failed-user-v1",
        "payment.failed",
        "payment_failed",
        "payment",
        "high",
        "order_owner",
        "payment-failed",
        "transactional_required",
        ["in_app", "email"],
        [],
    ),
    (
        "commerce-refund-succeeded-user-v1",
        "refund.succeeded",
        "refund_succeeded",
        "payment",
        "normal",
        "order_owner",
        "refund-succeeded",
        "transactional_required",
        ["in_app", "email"],
        [],
    ),
    (
        "commerce-subscription-activated-v1",
        "subscription.activated",
        "subscription_activated",
        "subscription",
        "normal",
        "subscription_owner",
        "subscription-activated",
        "service_required",
        ["in_app"],
        ["email"],
    ),
    (
        "activity-registration-confirmed-v1",
        "activity.registration.confirmed",
        "registration_confirmed",
        "activity",
        "normal",
        "activity_registration_user",
        "registration-confirmed",
        "service_required",
        ["in_app"],
        ["email"],
    ),
    (
        "activity-waitlist-promotion-v1",
        "activity.waitlist.promotion_offered",
        "waitlist_promotion",
        "activity",
        "high",
        "activity_waitlist_user",
        "waitlist-promotion",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "activity-checkin-available-v1",
        "activity.checkin.available",
        "checkin_available",
        "activity",
        "high",
        "activity_registration_user",
        "checkin-available",
        "service_required",
        ["in_app"],
        [],
    ),
    (
        "activity-cancelled-user-v1",
        "activity.cancelled",
        "activity_cancelled",
        "activity",
        "high",
        "activity_registration_user",
        "activity-cancelled",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "activity-mutual-choice-v1",
        "activity.mutual_choice.created",
        "mutual_choice_created",
        "matchmaking",
        "high",
        "event_user",
        "mutual-choice-created",
        "service_required",
        ["in_app"],
        [],
    ),
    (
        "relationship-reminder-due-v1",
        "relationships.reminder.due",
        "relationship_reflection_available",
        "relationship",
        "low",
        "event_user",
        "relationship-reflection-available",
        "service_optional",
        ["in_app"],
        [],
    ),
    (
        "membership-activated-v1",
        "membership.activated",
        "membership_activated",
        "membership",
        "high",
        "event_user",
        "membership-activated",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "membership-renewed-v1",
        "membership.renewed",
        "membership_renewed",
        "membership",
        "normal",
        "event_user",
        "membership-renewed",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "membership-grace-period-v1",
        "membership.grace_period",
        "membership_grace_period",
        "membership",
        "high",
        "event_user",
        "membership-grace-period",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "membership-cancel-scheduled-v1",
        "membership.cancel_scheduled",
        "membership_cancel_scheduled",
        "membership",
        "normal",
        "event_user",
        "membership-cancel-scheduled",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "membership-expired-v1",
        "membership.expired",
        "membership_expired",
        "membership",
        "high",
        "event_user",
        "membership-expired",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "membership-plan-changed-v1",
        "membership.upgraded",
        "membership_plan_changed",
        "membership",
        "high",
        "event_user",
        "membership-plan-changed",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "course-enrollment-activated-v1",
        "course.enrollment.activated",
        "enrollment_activated",
        "course",
        "normal",
        "course_enrollment_user",
        "enrollment-activated",
        "service_required",
        ["in_app"],
        ["email"],
    ),
    (
        "course-content-released-v1",
        "course.content.released",
        "content_released",
        "course",
        "normal",
        "course_enrollment_user",
        "content-released",
        "service_optional",
        ["in_app"],
        [],
    ),
    (
        "course-assignment-graded-v1",
        "course.exercise.graded",
        "assignment_graded",
        "course",
        "normal",
        "course_enrollment_user",
        "assignment-graded",
        "service_optional",
        ["in_app"],
        [],
    ),
    (
        "course-certificate-issued-v1",
        "course.certificate.issued",
        "certificate_issued",
        "course",
        "normal",
        "course_enrollment_user",
        "certificate-issued",
        "service_required",
        ["in_app"],
        ["email"],
    ),
    (
        "counseling-time-proposed-v1",
        "counseling.appointment.time_proposed",
        "appointment_time_proposed",
        "counseling",
        "normal",
        "counseling_appointment_user",
        "appointment-time-proposed",
        "service_required",
        ["in_app"],
        ["email"],
    ),
    (
        "counseling-confirmed-v1",
        "counseling.appointment.confirmed",
        "appointment_confirmed",
        "counseling",
        "high",
        "counseling_appointment_user",
        "appointment-confirmed",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "counseling-rescheduled-v1",
        "counseling.appointment.rescheduled",
        "appointment_rescheduled",
        "counseling",
        "high",
        "counseling_appointment_user",
        "appointment-rescheduled",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "counseling-cancelled-v1",
        "counseling.appointment.cancelled",
        "appointment_cancelled",
        "counseling",
        "high",
        "counseling_appointment_user",
        "appointment-cancelled",
        "service_required",
        ["in_app", "email"],
        [],
    ),
    (
        "counseling-summary-v1",
        "counseling.summary.published",
        "summary_published",
        "counseling",
        "normal",
        "counseling_appointment_user",
        "session-summary-published",
        "service_required",
        ["in_app"],
        [],
    ),
    (
        "counseling-action-due-v1",
        "counseling.action_item.due",
        "action_item_due",
        "counseling",
        "normal",
        "event_user",
        "action-item-due",
        "service_optional",
        ["in_app"],
        ["email"],
    ),
    (
        "counseling-followup-due-v1",
        "counseling.follow_up.due",
        "follow_up_due",
        "counseling",
        "normal",
        "event_user",
        "follow-up-due",
        "service_optional",
        ["in_app"],
        ["email"],
    ),
    (
        "ai-referral-created-v1",
        "ai.referral.created",
        "ai_referral_created",
        "ai_assistant",
        "high",
        "ai_referral_user",
        "referral-created",
        "service_required",
        ["in_app"],
        [],
    ),
    (
        "ai-referral-assigned-v1",
        "ai.referral.assigned",
        "ai_referral_assigned",
        "ai_assistant",
        "high",
        "ai_referral_user",
        "referral-assigned",
        "service_required",
        ["in_app"],
        [],
    ),
    (
        "ai-human-message-v1",
        "ai.human_advisor.message_created",
        "human_message_created",
        "ai_assistant",
        "high",
        "event_user",
        "human-message-created",
        "service_required",
        ["in_app"],
        [],
    ),
)


async def seed_notifications() -> None:
    async with session_factory() as session:
        for (
            code,
            event_type,
            notification_type,
            category,
            priority,
            resolver,
            template_code,
            preference_policy,
            required,
            optional,
        ) in SUBSCRIPTIONS:
            await session.execute(
                text(
                    "INSERT INTO notification_event_subscriptions "
                    "(subscription_code,source_event_type,source_event_version,notification_type,category,"
                    "priority,recipient_resolver_code,template_code,channel_policy,preference_policy,"
                    "scheduling_policy,deduplication_policy,status) VALUES (:code,:event_type,1,"
                    ":notification_type,:category,:priority,:resolver,:template_code,CAST(:channels AS jsonb),"
                    ":preference_policy,'{}'::jsonb,CAST(:dedup AS jsonb),'active') "
                    "ON CONFLICT (subscription_code) DO UPDATE SET status='active',updated_at=now()"
                ),
                {
                    "code": code,
                    "event_type": event_type,
                    "notification_type": notification_type,
                    "category": category,
                    "priority": priority,
                    "resolver": resolver,
                    "template_code": template_code,
                    "channels": json.dumps({"required": required, "optional": optional}),
                    "preference_policy": preference_policy,
                    "dedup": json.dumps({"format": "{event_type}:{event_id}:{user_id}"}),
                },
            )
        reminder_policies = (
            (
                "activity-start",
                "activity.registration.confirmed",
                [{"offset": "-P1D", "template_code": "activity-reminder"}],
            ),
            (
                "course-expiry",
                "course.enrollment.expiring",
                [{"offset": "-P7D", "template_code": "course-access-expiring"}],
            ),
            (
                "counseling-appointment",
                "counseling.appointment.confirmed",
                [
                    {"offset": "-P1D", "template_code": "appointment-reminder"},
                    {"offset": "-PT1H", "template_code": "appointment-reminder"},
                ],
            ),
        )
        for code, event_type, rules in reminder_policies:
            await session.execute(
                text(
                    "INSERT INTO notification_reminder_policies "
                    "(policy_code,semantic_version,source_event_type,reminder_rules,status) "
                    "VALUES (:code,'1.0.0',:event_type,CAST(:rules AS jsonb),'active') ON CONFLICT DO NOTHING"
                ),
                {"code": code, "event_type": event_type, "rules": json.dumps({"reminders": rules})},
            )
        await session.execute(
            text(
                "INSERT INTO notification_provider_health (provider,circuit_state) VALUES (:provider,'closed') "
                "ON CONFLICT (provider) DO NOTHING"
            ),
            {"provider": get_settings().notification_email_provider},
        )
        await session.commit()
    print(
        f"Notification seed complete: {len(SUBSCRIPTIONS)} subscriptions, "
        f"3 reminder policies, provider={get_settings().notification_email_provider}"
    )


if __name__ == "__main__":
    asyncio.run(seed_notifications())
