events {}

http {
  upstream vav_api_pool {
    server vav-platform-api-1:8000 max_fails=1 fail_timeout=1s;
    server vav-platform-api-ha-peer:8000 max_fails=1 fail_timeout=1s;
  }

  server {
    listen 8080;

    location / {
      proxy_pass http://vav_api_pool;
      proxy_connect_timeout 1s;
      proxy_read_timeout 3s;
      proxy_next_upstream error timeout http_502 http_503 http_504;
      proxy_next_upstream_tries 2;
    }
  }
}
