"""Member-facing recommendation API.

Every response is generated by the backend for one specific viewer. A member
receives their own list, their own explanation and their own settings; nothing
here can return another member's preferences, directional score or contact
details.
"""

# ruff: noqa: B008, E501
from __future__ import annotations

from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, Request
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from vav.api.dependencies import get_database_session
from vav.common.exceptions import VavError
from vav.common.schemas import success
from vav.core.config import get_settings
from vav.core.request_context import request_id_from_request
from vav.modules.identity.dependencies import AuthenticatedPrincipal, require_authenticated_user
from vav.modules.recommendations import batches, cold_start, explanations, service
from vav.modules.recommendations import feedback as feedback_service
from vav.modules.recommendations.domain import FEEDBACK_REASON_CODES
from vav.modules.recommendations.features import FEATURE_DEFINITIONS
from vav.modules.recommendations.schemas import (
    BatchRequest,
    ExposureRequest,
    FeedbackRequest,
    RecommendationSettingsRequest,
    TuningRequest,
)

router = APIRouter()


def _item_dto(item: dict[str, Any]) -> dict[str, Any]:
    """The only shape a member ever receives for a recommendation item.

    Directional scores stay server-side: a member never learns what the other
    member's engine thought of them, and no compatibility percentage is shown.
    """
    return {
        "recommendation_item_id": str(item["id"]),
        "rank_position": item["rank_position"],
        "status": item["status"],
        "profile": item["visible_profile_snapshot"],
        "explanation": explanations.member_view(item["explanation_snapshot"] or {}),
        "available_from": item["available_from"],
        "expires_at": item["expires_at"],
    }


@router.get("/recommendations")
async def list_recommendations(
    request: Request,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    service.enabled()
    user_id = principal.user.id
    entry = await service.pool_entry(session, user_id)
    settings_row = await service.user_settings(session, user_id)
    batch = await batches.active_batch(session, user_id)
    items = await batches.viewer_items(session, viewer_id=user_id) if batch else []

    payload: dict[str, Any] = {
        "eligible": bool(entry and entry["eligible"]),
        "ineligible_reason_codes": entry["eligibility_reasons"] if entry else ["no_pool_entry"],
        "recommendations_paused": settings_row["recommendations_paused"],
        "batch": None,
        "items": [_item_dto(item) for item in items],
        "empty_state": None,
    }
    if batch is not None:
        payload["batch"] = {
            "batch_id": str(batch["id"]),
            "batch_number": batch["batch_number"],
            "batch_type": batch["batch_type"],
            "status": batch["status"],
            "generated_size": batch["generated_size"],
            "expires_at": batch["expires_at"],
        }
    if not payload["items"]:
        report = service._jsonb(batch["generation_report"]) if batch else {}
        payload["empty_state"] = {
            "available_actions": list(cold_start.EMPTY_RESULT_ACTIONS),
            "most_restrictive_criteria": [
                {"criterion_code": code, "excluded_count": count}
                for code, count in sorted(
                    (report or {}).get("hard_constraint_failures", {}).items(),
                    key=lambda pair: (-pair[1], pair[0]),
                )[:5]
            ],
            "cold_start": (report or {}).get("cold_start"),
        }
    return success(payload, request_id_from_request(request))


@router.post("/recommendations/batches")
async def request_batch(
    request: Request,
    payload: BatchRequest,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    """Request today's batch or a supplemental one.

    Repeat calls return the existing batch, so refreshing can never buy extra
    recommendations beyond the daily budget.
    """
    service.enabled()
    batch = await batches.generate_batch(
        session,
        principal.user.id,
        batch_type=payload.batch_type,
        requested_size=payload.requested_size,
    )
    await session.commit()
    return success(
        {
            "batch_id": str(batch["id"]),
            "batch_type": batch["batch_type"],
            "status": batch["status"],
            "generated_size": batch["generated_size"],
            "expires_at": batch["expires_at"],
        },
        request_id_from_request(request),
    )


@router.get("/recommendations/{item_id}")
async def get_recommendation(
    request: Request,
    item_id: UUID,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    service.enabled()
    items = await batches.viewer_items(session, viewer_id=principal.user.id)
    for item in items:
        if item["id"] == item_id:
            return success(_item_dto(item), request_id_from_request(request))
    raise VavError("RECOMMENDATION_ITEM_NOT_FOUND", "Recommendation not found.", status_code=404)


@router.post("/recommendations/{item_id}/exposures")
async def record_exposure(
    request: Request,
    item_id: UUID,
    payload: ExposureRequest,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    result = await batches.record_exposure(
        session,
        viewer_id=principal.user.id,
        item_id=item_id,
        exposure_type=payload.exposure_type,
        duration_ms=payload.duration_ms,
        source=payload.source,
    )
    await session.commit()
    return success(result, request_id_from_request(request))


@router.post("/recommendations/{item_id}/feedback")
async def submit_feedback(
    request: Request,
    item_id: UUID,
    payload: FeedbackRequest,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    """Record the feedback a member may give from a recommendation card.

    Likes, skips, withdrawals and introductions belong to the interaction
    module; this endpoint accepts only viewing signals and 'not relevant'.
    """
    row = (
        await session.execute(
            text(
                "SELECT recommended_user_id FROM recommendation_items WHERE id=:id AND viewer_user_id=:viewer"
            ),
            {"id": item_id, "viewer": principal.user.id},
        )
    ).mappings()
    item = row.first()
    if item is None:
        raise VavError(
            "RECOMMENDATION_ITEM_NOT_FOUND", "Recommendation not found.", status_code=404
        )
    result = await feedback_service.ingest(
        session,
        viewer_user_id=principal.user.id,
        recommended_user_id=item["recommended_user_id"],
        feedback_type=payload.feedback_type,
        recommendation_item_id=item_id,
        reason_code=payload.reason_code,
        reason_details=payload.reason_details,
        source_module="user_web",
        from_member=True,
    )
    await session.commit()
    return success(result, request_id_from_request(request))


@router.get("/account/recommendation-preferences")
async def get_preferences(
    request: Request,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    settings_row = await service.user_settings(session, principal.user.id)
    tuning = await service.tuning_profile(session, principal.user.id)
    return success(
        {
            "settings": {
                "recommendations_paused": settings_row["recommendations_paused"],
                "daily_received_limit": settings_row["daily_received_limit"],
                "delivery_frequency": settings_row["delivery_frequency"],
                "extended_recommendations_enabled": settings_row[
                    "extended_recommendations_enabled"
                ],
                "relaxable_criteria": settings_row["relaxable_criteria"],
                "preferred_locale": settings_row["preferred_locale"],
            },
            "tuning": {
                "exploration_level": tuning["exploration_level"],
                "feedback_personalization_enabled": tuning["feedback_personalization_enabled"],
                "adjusted_feature_count": len(tuning["feature_weight_adjustments"]),
            },
            "maximum_daily_received": get_settings().recommendation_max_daily_received,
            "feedback_reason_codes": list(FEEDBACK_REASON_CODES),
        },
        request_id_from_request(request),
    )


@router.put("/account/recommendation-preferences")
async def update_preferences(
    request: Request,
    payload: RecommendationSettingsRequest,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    updated = await service.update_user_settings(
        session, principal.user.id, payload.model_dump(exclude_none=True)
    )
    await session.commit()
    return success(
        {
            "recommendations_paused": updated["recommendations_paused"],
            "daily_received_limit": updated["daily_received_limit"],
            "delivery_frequency": updated["delivery_frequency"],
            "extended_recommendations_enabled": updated["extended_recommendations_enabled"],
            "relaxable_criteria": updated["relaxable_criteria"],
            "preferred_locale": updated["preferred_locale"],
            "settings_version": updated["settings_version"],
        },
        request_id_from_request(request),
    )


@router.put("/account/recommendation-tuning")
async def update_tuning(
    request: Request,
    payload: TuningRequest,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    tuning = await feedback_service.update_tuning(
        session,
        principal.user.id,
        feedback_personalization_enabled=payload.feedback_personalization_enabled,
        exploration_level=payload.exploration_level,
    )
    await session.commit()
    return success(
        {
            "exploration_level": tuning["exploration_level"],
            "feedback_personalization_enabled": tuning["feedback_personalization_enabled"],
            "tuning_version": tuning["tuning_version"],
        },
        request_id_from_request(request),
    )


@router.post("/account/recommendation-tuning/reset")
async def reset_tuning(
    request: Request,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    tuning = await feedback_service.reset_tuning(session, principal.user.id)
    await session.commit()
    return success(
        {
            "tuning_version": tuning["tuning_version"],
            "adjusted_feature_count": len(tuning["feature_weight_adjustments"]),
        },
        request_id_from_request(request),
    )


@router.get("/account/recommendation-history")
async def recommendation_history(
    request: Request,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    rows = (
        await session.execute(
            text(
                "SELECT id, batch_number, batch_type, status, generated_size, created_at, expires_at "
                "FROM recommendation_batches WHERE user_id=:user_id ORDER BY batch_number DESC LIMIT 50"
            ),
            {"user_id": principal.user.id},
        )
    ).mappings()
    return success(
        {
            "batches": [
                {
                    "batch_id": str(row["id"]),
                    "batch_number": row["batch_number"],
                    "batch_type": row["batch_type"],
                    "status": row["status"],
                    "generated_size": row["generated_size"],
                    "created_at": row["created_at"],
                    "expires_at": row["expires_at"],
                }
                for row in rows
            ]
        },
        request_id_from_request(request),
    )


@router.get("/account/recommendation-transparency")
async def transparency(
    request: Request,
    principal: AuthenticatedPrincipal = Depends(require_authenticated_user),
    session: AsyncSession = Depends(get_database_session),
) -> dict[str, Any]:
    """Explain, for this member, what the engine used and what it did not.

    The page describes categories, the member's own settings and the platform
    defaults; it never shows another member's data or the internal weights of
    an individual recommendation.
    """
    criteria = await service.preference_criteria(session, principal.user.id)
    stated = {str(item["criterion_code"]) for item in criteria}
    tuning = await service.tuning_profile(session, principal.user.id)
    projection = await service.projection_for(session, principal.user.id)
    payload = service.projection_payload(projection) if projection else {}

    used: list[dict[str, Any]] = []
    for definition in FEATURE_DEFINITIONS:
        source = (
            "your_stated_preference" if definition.criterion_code in stated else "platform_default"
        )
        lookup = definition.criterion_code or definition.similarity_code
        known = bool(payload.get(lookup)) if lookup in payload else None
        used.append(
            {
                "feature_group": definition.feature_group,
                "feature_code": definition.feature_code,
                "source": source,
                "user_configurable": definition.user_configurable,
                "your_information_available": known,
            }
        )

    return success(
        {
            "data_categories_used": sorted(
                {definition.feature_group for definition in FEATURE_DEFINITIONS}
            ),
            "features": used,
            "hard_constraints_from_you": sorted(
                str(item["criterion_code"]) for item in criteria if item.get("hard_constraint")
            ),
            "never_used": [
                "photo_attractiveness",
                "ai_conversations",
                "counseling_records",
                "payment_history",
                "health_or_personality_inference",
            ],
            "behavioural_personalization_enabled": tuning["feedback_personalization_enabled"],
            "how_to_adjust": [
                "update_partner_preferences",
                "change_relaxable_criteria",
                "change_exploration_level",
                "disable_behavioural_personalization",
                "pause_recommendations",
            ],
        },
        request_id_from_request(request),
    )
